#!/usr/bin/env bash

mkdir -p /storage/valid-gems

cd /storage/rubygems-mirror/gems

while read gem
do
    if [ -f /storage/valid-gems/$gem ] && [ $(stat -c '%s' $gem) = $(stat -c '%s' /storage/valid-gems/$gem) ]
    then
        continue
    else
        cp $gem /storage/valid-gems
    fi
done < /storage/rubygems-mirror/valid

for dir in /storage/machines/*
do
    if [ -d $dir ]
    then
        rsync -az /storage/valid-gems $dir
    fi
done
