#!/usr/bin/env bash

mkdir -p /storage/valid-gems

cd /storage/rubygems-mirror/gems

while read gem
do
    cp $gem /storage/valid-gems
done < /storage/rubygems-mirror/valid

for dir in /storage/machines/*
do
    if [ -d $dir ]
    then
        cp -R /storage/valid-gems $dir
    fi
done
