#!/bin/sh

case "$1" in
  start)
    cd /test/heartbeat
    sudo -u test /usr/local/rvm/bin/rvm-shell "1.9.2" -c "thin -d -p 8000 -P /test/heartbeat/thin.pid start"
  ;;
  stop) 
    kill $(cat /test/heartbeat/thin.pid)
  ;;
  restart)
    $0 stop
    $0 start
  ;;
esac
